{
 "title": "Backend API Health",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "P99 API Latency",
   "type": "barchart",
   "description": "How long it takes the server to respond to the client. P99 means that 99% of all requests are processed within this time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, endpoint) (rate(fatigue_api_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Requests per Second (RPS)",
   "type": "timeseries",
   "description": "Shows how many frames/requests per second arrive at the backend",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": {
    "defaults": {
     "unit": "Throughput / requests per second (rps)"
    }
   },
   "targets": [
    {
     "expr": "sum by(endpoint, status_code) (rate(fatigue_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{endpoint}} - HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"docker-backend-1\"} |= ``"
    }
   ]
  },
  {
   "title": "API Errors (4xx, 5xx)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(endpoint, status_code) (increase(fatigue_api_requests_total{status_code=~\"^[45].*\"}[$__rate_interval]))",
     "legendFormat": "{{endpoint}} - {{status_code}}"
    }
   ]
  }
 ]
}